version: '3.8'

services:
  postgres_db:
    image: pgvector/pgvector:pg17
    container_name: fastapp_postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapp_test
    ports:
      - "5432:5432" # Expose port 5432 locally
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fastapp_test"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local