/**
 * A lib for all user management related functions
 */

import {
  addUserToOrganisation,
  addUserToTeam,
  getUser,
  getUserByEmail,
  getUserById,
  getUserOrganisations,
  getUserTeams,
  removeUserFromOrganisation,
  removeUserFromTeam,
  updateUser,
} from "./lib/usermanagement/user";
import {
  addOrganisationMember,
  addTeamMember,
  assignPermissionToGroup,
  createOrganisation,
  createPathPermission,
  createPermissionGroup,
  createTeam,
  deleteOrganisation,
  deletePathPermission,
  deletePermissionGroup,
  deleteTeam,
  getLastOrganisation,
  getOrganisation,
  getOrganisationMembers,
  getPathPermission,
  getPermissionGroup,
  getPermissionGroupsByOrganisation,
  getPermissionsByOrganisation,
  getTeam,
  getTeamsAndMembersByOrganisation,
  getTeamsByOrganisation,
  removeOrganisationMember,
  removePermissionFromGroup,
  removeTeamMember,
  setLastOrganisation,
  updateOrganisation,
  updatePathPermission,
  updatePermissionGroup,
  updateTeam,
} from "./lib/usermanagement/oganisations-and-teams";
import {
  acceptAllPendingInvitationsForUser,
  acceptOrganisationInvitation,
  createOrganisationInvitation,
  declineOrganisationInvitation,
  getAllOrganisationInvitations,
} from "./lib/usermanagement/invitations";

export default {
  // users
  getUser,
  getUserById,
  getUserByEmail,
  updateUser,
  addUserToOrganisation,
  removeUserFromOrganisation,
  getUserTeams,
  addUserToTeam,
  removeUserFromTeam,
  getUserOrganisations,
  // organisations
  createOrganisation,
  getOrganisation,
  updateOrganisation,
  deleteOrganisation,
  // teams
  createTeam,
  getTeam,
  updateTeam,
  deleteTeam,
  getTeamsByOrganisation,
  addTeamMember,
  removeTeamMember,
  // permission groups
  createPermissionGroup,
  updatePermissionGroup,
  deletePermissionGroup,
  getPermissionGroup,
  getPermissionGroupsByOrganisation,
  // path permissions
  createPathPermission,
  getPathPermission,
  updatePathPermission,
  deletePathPermission,
  // invitations
  getAllOrganisationInvitations,
  acceptOrganisationInvitation,
  declineOrganisationInvitation,
  createOrganisationInvitation,
  acceptAllPendingInvitationsForUser,
  assignPermissionToGroup,
  removePermissionFromGroup,
  getLastOrganisation,
  setLastOrganisation,
  getTeamsAndMembersByOrganisation,
  getPermissionsByOrganisation,
  addOrganisationMember,
  removeOrganisationMember,
  getOrganisationMembers,
};
