name: Generate DB Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main        

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Generate DB Docs
        run: bun run scripts/generate-db-doc.ts
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: db-schema-doc
          path: docs/db-schema.md
      - name: Commit documentation
            run: |
              if [ -n "$(git status --porcelain docs/db-schema.md)" ]; then
                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"
                git add docs/README_Jobs_API.md
                git commit -m "chore: update job service docs"
                git push
              fi
            env:
              GITHUB_TOKEN: ${{ secrets.BE_GH_REPO_KEY }}
