name: Generate DB Documentation

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/lib/db/schema/**'
      - '.github/workflows/db-docs.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Generate DB Docs
        run: bun run scripts/generate-db-doc.ts
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: db-schema-doc
          path: docs/db-schema.md
